<a href="https://colab.research.google.com/github/KBVKarthik/Tensorflow-Practice/blob/main/Quick_Start_Beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.4752216 ,  0.28835526, -1.1091865 , -0.54205436, -0.584093  ,
        -0.7125002 , -0.2520749 , -0.1951876 , -1.2412392 , -0.37796348]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09580769, 0.20559739, 0.05082447, 0.08961388, 0.08592472,
        0.07557038, 0.11975998, 0.12677032, 0.04453722, 0.10559394]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.5826907

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2968 - accuracy: 0.9120
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1442 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1087 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0875 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0750 - accuracy: 0.9765


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0719 - accuracy: 0.9779


[0.07189736515283585, 0.9779000282287598]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4716495e-07, 1.4497480e-08, 8.2010856e-06, 1.1765140e-03,
        9.5435118e-12, 2.5101807e-07, 2.2089607e-13, 9.9879968e-01,
        6.3953198e-06, 8.8073293e-06],
       [5.3877731e-08, 1.2491066e-03, 9.9868172e-01, 6.5082269e-05,
        1.2611249e-13, 3.7676693e-06, 4.6276236e-09, 1.5633265e-12,
        3.3374084e-07, 5.4160964e-12],
       [1.7540517e-08, 9.9868172e-01, 9.6205076e-05, 4.0658342e-06,
        1.0505668e-05, 1.1832242e-06, 7.6480164e-06, 1.0957917e-03,
        1.0267890e-04, 2.3463981e-07],
       [9.9993372e-01, 2.9910520e-08, 7.1971940e-06, 1.2429655e-06,
        1.7818774e-06, 2.7965352e-05, 1.2783729e-05, 5.3552071e-06,
        1.9483650e-08, 9.9008439e-06],
       [4.1788312e-06, 2.6060471e-07, 1.7089432e-04, 1.3203310e-06,
        9.8572147e-01, 1.2676838e-07, 1.2542317e-06, 4.4619155e-05,
        5.8671103e-06, 1.4049965e-02]], dtype=float32)>